# permissions for end users to view namespacelabels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: namespacelabel-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: namespacelabel
    app.kubernetes.io/part-of: namespacelabel
    app.kubernetes.io/managed-by: kustomize
  name: namespacelabel-viewer-role
rules:
- apiGroups:
  - dana.io.dana.io
  resources:
  - namespacelabels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dana.io.dana.io
  resources:
  - namespacelabels/status
  verbs:
  - get
