apiVersion: dana.io.dana.io/v1alpha1
kind: NamespaceLabel
metadata:
  labels:
    app.kubernetes.io/name: namespacelabel
    app.kubernetes.io/instance: namespacelabel-sample
    app.kubernetes.io/part-of: namespacelabel
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: namespacelabel
  name: namespacelabel-sample
spec:
  # TODO(user): Add fields here
